### PR TITLE
add `policy_std` column for resources that support resource policies to standardize policy structure for searching.closes #69

### LINKED ISSUE #69: add `policy_std` column for resources that support resource policies to standardize policy structure for searching
add `policy_std` column for resources that support resource policies to standardize policy structure for searching (as we do for AWS.

For example, this
```json
 {                                                               
     "Version": "1",                                             
     "Statement": [                                              
         {                                                       
             "Action": "oss:Get*",
             "Effect": "Allow",
             "Resource":  "acs:oss:*:1234567890123456:my-public-bucket/*",
             "Principal": "*"
         }                                                       
     ]                                                           
 }  
```
 to something like this:
```json
 {                                                               
     "Version": "1",                                             
     "Statement": [                                              
         {                                                       
             "Action": [
                 "oss:Get*"
             ],                               
             "Effect": "Allow",                                  
             "Resource": [                                       
                 "acs:oss:*:1234567890123456:my-public-bucket/*" 
             ],                                                  
             "Principal": [
                 "*"
             ]                                 
         }                                                       
     ]                                                           
 }  
```

### PR DESCRIPTION
**Pull request by bigdatasourav**

### CODE REVIEW

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@bigdatasourav For each column that you changed, can you please show an example query + result for at least 1 row with data in that column? I'd like to see how the formatted policies look.

**Comment by bigdatasourav** [comment]
```> select jsonb_pretty(assume_role_policy_document) as policy,jsonb_pretty(assume_role_policy_document_std) as policy_std from alicloud.alicloud_ram_role where name = 'AliyunCSManagedCsiRole'
+-----------------------------------------+---------------------------------------+
| policy                                  | policy_std                            |
+-----------------------------------------+---------------------------------------+
| {                                       | {                                     |
|     "Version": "1",                     |     "Version": "1",                   |
|     "Statement": [                      |     "Statement": [                    |
|         {                               |         {                             |
|             "Action": "sts:AssumeRole", |             "Action": [               |
|             "Effect": "Allow",          |                 "sts:assumerole"      |
|             "Principal": {              |             ],                        |
|                 "Service": [            |             "Effect": "Allow",        |
|                     "cs.aliyuncs.com"   |             "Principal": {            |
|                 ]                       |                 "Service": [          |
|             }                           |                     "cs.aliyuncs.com" |
|         }                               |                 ]                     |
|     ]                                   |             }                         |
| }                                       |         }                             |
|                                         |     ]                                 |
|                                         | }                                     |
+-----------------------------------------+---------------------------------------+
>

**Comment by bigdatasourav** [comment]
```
For OSS_bucket policy is already in std format -
> select jsonb_pretty(policy) as policy from alicloud.alicloud_oss_bucket where name ='cis-test2'
+----------------------------------------------------------+
| policy                                                   |
+----------------------------------------------------------+
| {                                                        |
|     "Version": "1",                                      |
|     "Statement": [                                       |
|         {                                                |
|             "Action": [                                  |
|                 "oss:*"                                  |
|             ],                                           |
|             "Effect": "Allow",                           |
|             "Resource": [                                |
|                 "acs:oss:*:5982111499156037:cis-test2",  |
|                 "acs:oss:*:5982111499156037:cis-test2/*" |
|             ],                                           |
|             "Principal": [                               |
|                 "233835915370490155"                     |
|             ]                                            |
|         }                                                |
|     ]                                                    |
| }                                                        |
+----------------------------------------------------------+
>

**Comment by cbruno10** [comment]
@bigdatasourav Can you please show an example query that has data in the modified columns (`attached_policy`) in the `alicloud_ram_user` and `alicloud_ram_group` tables?

Also, for the OSS bucket policy, I can see the column is defined as:
```
{
    Name:        "policy",
    Type:        proto.ColumnType_JSON,
    Hydrate:     getBucketPolicy,
    Transform:   transform.FromValue().Transform(transform.UnmarshalYAML),
    Description: "Allows you to grant permissions on OSS resources to RAM users from your Alibaba Cloud and other Alibaba Cloud accounts. You can also control access based on the request source.",
},
```

What does `transform.UnmarshalYAML` do? Does the Alicloud API return lists of strings (even if there's only one item in it), or does this transform function convert single strings into a list of strings?

**Comment by bigdatasourav** [comment]
```
> select jsonb_pretty(attached_policy) as attached_policy from alicloud_ram_group where name = 'warehouse'
+-----------------------------------------------------------+
| attached_policy                                           |
+-----------------------------------------------------------+
| [                                                         |
|     {                                                     |
|         "AttachDate": "2021-02-25T00:37:11Z",             |
|         "PolicyName": "AliyunOSSReadOnlyAccess",          |
|         "PolicyType": "System",                           |
|         "Description": "只读访问对象存储服务(OSS)的权限", |
|         "DefaultVersion": "v1"                            |
|     },                                                    |
|     {                                                     |
|         "AttachDate": "2021-02-25T00:37:11Z",             |
|         "PolicyName": "AliyunECSReadOnlyAccess",          |
|         "PolicyType": "System",                           |
|         "Description": "只读访问云服务器服务(ECS)的权限", |
|         "DefaultVersion": "v3"                            |
|     }                                                     |
| ]                                                         |
+-----------------------------------------------------------+
>

**Comment by bigdatasourav** [comment]
```
> select jsonb_pretty(attached_policy) as attached_policy from alicloud_ram_user where name ='sourav'
+----------------------------------------------------+
| attached_policy                                    |
+----------------------------------------------------+
| [                                                  |
|     {                                              |
|         "AttachDate": "2021-02-18T06:02:09Z",      |
|         "PolicyName": "AdministratorAccess",       |
|         "PolicyType": "System",                    |
|         "Description": "管理所有阿里云资源的权限", |
|         "DefaultVersion": "v1"                     |
|     }                                              |
| ]                                                  |
+----------------------------------------------------+
>

**Comment by bigdatasourav** [comment]
UnmarshalYAML transform function convert the string to json object, as the Hydrate method here returns a stringify json.

**Review by cbruno10 — APPROVED** [review]

**Pull request merged**
